### PR TITLE
Adding section about using UT3 user

### PR DESCRIPTION
**Pull request by hkorsvoll**
UT3 user should not be used when running tests. This should be mentioned in the readme.

### CODE REVIEW

**Comment by pesse** [comment]
Thank you, @hkorsvoll!
We have a problem with our Travis build - I will merge as soon as we managed to solve it.

**Comment by jgebal** [comment]
@hkorsvoll  - thank you for the suggested change.
I think we should fix it in the framework or update framework core documentation.

The statement is not entirely true and issues will occur only under very specific circumstances today.
Hopefully, we will be able to fix it in next release.

**Comment by jgebal** [comment]
@pesse - PR will not work as the forked repo doesn't have access to our docker images.

**Comment by pesse** [comment]
Ah, sure - you're right on both.
I would probably still add the recommendation not to run cli as ut3 - or am I missing something?

**Comment by jgebal** [comment]
Well.
If you're installing utPLSQL into your local schema and are running tests in that schema - that is unit tests are co-located with framework, then this advice would be inapplicable.

So if all you can do is use single schema (like in liveSQL), then that recommendation is not valid at all.

The only time this recommendation would be valid is when you have tests in other schema than framework owner and you still connect as framework owner to run your tests.

In that case I would recommend connecting as test packages owner or a different user, that has `execute any procedure` privilege.

By the way, I'm finishing a fix that should address the issue reported.

**Comment by pesse** [comment]
@hkorsvoll I will close this PR due to Jacek's insights, but thanks a lot for your engagement.
@jgebal I think it would be helpful to have an additional section in the Installation part of the user manual that shows best practices for User/Schema/Rights setup in different situations.
I'll create an issue and try to address that in the upcoming months (will be a good training for me)

**Pull request closed without merging**
