### PR TITLE
Fix connection string pattern for service names containing "_" or "."

### PR DESCRIPTION
**Pull request by dmvolodin**
Service name in connect string may contains "_" or "."(for domain specify)

### CODE REVIEW

**Comment by viniciusam** [comment]
Refactored how the connection string is parsed, see #16.

**Comment by jgebal** [comment]
I like the refactoring. No need to use regex to parse and split connection string.

**Comment by dmvolodin** [comment]
Great!
By the way, as i can see, we can not pass SID inside connect string.
It may be very simple with 3(4) separate parameters.
Something like this:
```java    
public String getConnectionUrl() throws Exception {
        if (getSid() != null && getServiceName() != null) {
            throw new Exception("SID and ServiceName can not be set both");
        }
        if (getSid() != null) {
            return String.format("jdbc:oracle:thin:@%s:%d:%s", getHost(), getPort(), getSid());
        } else {
            return String.format("jdbc:oracle:thin:@//%s:%d/%s", getHost(), getPort(), getServiceName());
        }
    }
```

**Comment by viniciusam** [comment]
Thanks for your contribution @dmvolodin. I will merge the refactoring changes and create an issue for the SID support.

**Pull request closed without merging**
