### PR TITLE
Custom file mapping support

### PR DESCRIPTION
**Pull request by viniciusam**
See: [https://github.com/utPLSQL/utPLSQL-java-api/pull/14](https://github.com/utPLSQL/utPLSQL-java-api/pull/14)

For now, custom mapping only works if you pass all parameters.
On demo project, you will need to add the owner subfolder.

### CODE REVIEW

**Comment by jgebal** [comment]
Nice work @viniciusam, thanks!

**Comment by viniciusam** [comment]
Closes #24

**Comment by jgebal** [comment]
@viniciusam 
Why it's all or nothing (no defaults)? Is it again the DB-side API thing?
If you would pass all params as null's to DB and DB would use defaults for nulls would that work?

**Comment by viniciusam** [comment]
That was because the way the API was handling default parameters, but we already changed that behaviour on:
https://github.com/utPLSQL/utPLSQL/commit/26b7d3dd5c5983689802e1fa56a52b7ef27c78a2

Using it on a utPLSQL develop install should work with defaults.

**Pull request merged**
